name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Heroku Container Registry
        uses: heroku/actions/setup@v2
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      - name: Build Docker image
        run: docker build -t registry.heroku.com/helperbot/web .

      - name: Push to Heroku Container Registry
        run: docker push registry.heroku.com/helperbot/web

      - name: Release
        run: heroku container:release web -a helperbot
