name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Heroku and set up container
        uses: akhileshns/heroku-deploy@v4.2.0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: helperbot
          heroku_email: <your-heroku-email>
          docker_build: true

      - name: Release
        run: heroku container:release web -a helperbot
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
